### ISSUE TITLE
A problem with code running on the GPU

### ISSUE THREAD

**Issue by lemonhu** [achernodub/bilstm-cnn-crf-tagger#2]
Thanks for your contributions.
when I run the code, I found it run slowly on GPU. And then, I tried to print the is_cuda state of the layers, such as the "is_cuda()" of the layer_bilstm, the output result was "False", Did it mean that the program was not running on the GPU?

**Comment by achernodub** [comment]
Hi @lemonhu! Sorry for a so long delay with the answer. Yes, if `is_cuda` method of some layer returns `False`, this means that actually, it was running not on GPU. Please, check that you use param `gpu` > -1 (0, for example).

**Comment by lemonhu** [comment]
Oh, I understand, thank you for your reply.
